package dev.lasm.foodcraft.init;

import dev.lasm.foodcraft.FoodCraft;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ModItems {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, FoodCraft.MOD_ID);
    public static final RegistryObject<Item> RICE_PORRIDGE;

    // Plants
    public static final RegistryObject<Item> CORN;
    public static final RegistryObject<Item> CUCUMBER;
    public static final RegistryObject<Item> EGGPLANT;
    public static final RegistryObject<Item> FACING_HEAVEN_PEPPER;
    public static final RegistryObject<Item> GREEN_PEPPER;
    public static final RegistryObject<Item> PEANUT;
    public static final RegistryObject<Item> RICE;
    public static final RegistryObject<Item> STICKY_RICE;
    public static final RegistryObject<Item> SWEET_POTATO;
    public static final RegistryObject<Item> TOMATO;
    public static final RegistryObject<Item> WHITE_RADISH;
    public static final RegistryObject<Item> CABBAGE;
    public static final RegistryObject<Item> STRAWBERRY;
    public static final RegistryObject<Item> GRAPEFRUIT;
    public static final RegistryObject<Item> CHERRY;
    public static final RegistryObject<Item> COCONUT;
    public static final RegistryObject<Item> BANANA;
    public static final RegistryObject<Item> PEACH;
    public static final RegistryObject<Item> PERSIMMON;
    public static final RegistryObject<Item> POMEGRANATE;
    public static final RegistryObject<Item> HAWTHORN;
    public static final RegistryObject<Item> LOQUAT;
    public static final RegistryObject<Item> LEMON;
    public static final RegistryObject<Item> PAPAYA;
    public static final RegistryObject<Item> LONGAN;
    public static final RegistryObject<Item> MANGO;
    public static final RegistryObject<Item> LITCHI;
    public static final RegistryObject<Item> PEAR;
    public static final RegistryObject<Item> ORANGE;
    public static final RegistryObject<Item> DATE;
    public static final RegistryObject<Item> GREEN_ONION;

    public static final RegistryObject<Item> GRAPEFRUIT_ICE_CREAM;
    public static final RegistryObject<Item> CHERRY_ICE_CREAM;
    public static final RegistryObject<Item> COCONUT_ICE_CREAM;
    public static final RegistryObject<Item> BANANA_ICE_CREAM;
    public static final RegistryObject<Item> PEACH_ICE_CREAM;
    public static final RegistryObject<Item> PERSIMMON_ICE_CREAM;
    public static final RegistryObject<Item> POMEGRANATE_ICE_CREAM;
    public static final RegistryObject<Item> HAWTHORN_ICE_CREAM;
    public static final RegistryObject<Item> LOQUAT_ICE_CREAM;
    public static final RegistryObject<Item> LEMON_ICE_CREAM;
    public static final RegistryObject<Item> PAPAYA_ICE_CREAM;
    public static final RegistryObject<Item> LONGAN_ICE_CREAM;
    public static final RegistryObject<Item> MANGO_ICE_CREAM;
    public static final RegistryObject<Item> LITCHI_ICE_CREAM;
    public static final RegistryObject<Item> PEAR_ICE_CREAM;
    public static final RegistryObject<Item> ORANGE_ICE_CREAM;
    public static final RegistryObject<Item> DATE_ICE_CREAM;

    public static final RegistryObject<Item> GRAPEFRUIT_JAM;
    public static final RegistryObject<Item> CHERRY_JAM;
    public static final RegistryObject<Item> COCONUT_JAM;
    public static final RegistryObject<Item> BANANA_JAM;
    public static final RegistryObject<Item> PEACH_JAM;
    public static final RegistryObject<Item> PERSIMMON_JAM;
    public static final RegistryObject<Item> POMEGRANATE_JAM;
    public static final RegistryObject<Item> HAWTHORN_JAM;
    public static final RegistryObject<Item> LOQUAT_JAM;
    public static final RegistryObject<Item> LEMON_JAM;
    public static final RegistryObject<Item> PAPAYA_JAM;
    public static final RegistryObject<Item> LONGAN_JAM;
    public static final RegistryObject<Item> MANGO_JAM;
    public static final RegistryObject<Item> LITCHI_JAM;
    public static final RegistryObject<Item> PEAR_JAM;
    public static final RegistryObject<Item> ORANGE_JAM;
    public static final RegistryObject<Item> DATE_JAM;

    public static final RegistryObject<Item> CHOCOLATE_DUST;
    public static final RegistryObject<Item> IRON_PLATE;
    public static final RegistryObject<Item> PURIFIED_WATER;
    public static final RegistryObject<Item> MILLED_RICE;
    public static final RegistryObject<Item> FLOUR;
    public static final RegistryObject<Item> PEANUT_OIL;
    public static final RegistryObject<Item> CIRCUIT;
    public static final RegistryObject<Item> DOUGH;
    public static final RegistryObject<Item> DUMPLING_MEAT;
    public static final RegistryObject<Item> SALT;
    public static final RegistryObject<Item> SOY_SAUCE;
    public static final RegistryObject<Item> VINEGAR;
    public static final RegistryObject<Item> POTATO_SLICED;
    public static final RegistryObject<Item> POTATO_SHREDDED;
    public static final RegistryObject<Item> PIXIAN_WATERCRESS;
    public static final RegistryObject<Item> STARCHES;
    public static final RegistryObject<Item> ZONGYE;
    public static final RegistryObject<Item> CURRY;
    public static final RegistryObject<Item> STICKY_RICE_FLOUR;
    public static final RegistryObject<Item> STICKY_RICE_DOUGH;
    public static final RegistryObject<Item> PEANUT_TANGYUAN_STUFFING;
    public static final RegistryObject<Item> CHICKEN_LARGE;
    public static final RegistryObject<Item> CHICKEN_MEDIUM;
    public static final RegistryObject<Item> CHICKEN_SMALL;
    public static final RegistryObject<Item> TOFU_SHREDDED;
    public static final RegistryObject<Item> CARROT_SHREDDED;
    public static final RegistryObject<Item> DOUGH_SHREDDED;
    public static final RegistryObject<Item> LAWEI_FLAVOR;
    public static final RegistryObject<Item> WHITE_RADISH_SHREDDED;
    public static final RegistryObject<Item> RED_BEAN_PASTE;
    public static final RegistryObject<Item> JINKELA;
    public static final RegistryObject<Item> OVERCOOKED_FOOD;

    public static final RegistryObject<Item> EGG_CUSTARD;
    public static final RegistryObject<Item> MUSHROOM_EGG_SOUP;
    public static final RegistryObject<Item> MUSHROOM_CHICKEN_SOUP;
    public static final RegistryObject<Item> NOODLES;
    public static final RegistryObject<Item> CROSSING_BRIDGE_NOODLES;
    public static final RegistryObject<Item> PASTA;
    public static final RegistryObject<Item> PRESERVED_EGG_PORRIDGE;
    public static final RegistryObject<Item> CHANGFEN;
    public static final RegistryObject<Item> LABA_PORRIDGE;
    public static final RegistryObject<Item> TOMATO_FRIED_EGG_RICE;
    public static final RegistryObject<Item> DISANXIAN_RICE;
    public static final RegistryObject<Item> SHREDDED_PORK_RICE;
    public static final RegistryObject<Item> KUNG_PAO_CHICKEN_RICE;
    public static final RegistryObject<Item> FRIED_SHREDDED_POTATO_RICE;
    public static final RegistryObject<Item> FISH_HEAD_RICE;
    public static final RegistryObject<Item> MAPO_TOFU_RICE;
    public static final RegistryObject<Item> PORK_BRAISED_IN_BROWN_SAUCE_RICE;
    public static final RegistryObject<Item> TWICE_COOKED_PORK_SLICES_RICE;
    public static final RegistryObject<Item> ORLEAN_CHICKEN_WINGS_RICE;
    public static final RegistryObject<Item> SLICED_COLD_CHICKEN;
    public static final RegistryObject<Item> SCALLION_CHICKEN;
    public static final RegistryObject<Item> CHICKEN_WITH_CHILI_SAUCE;
    public static final RegistryObject<Item> PEPPERY_CHICKEN;
    public static final RegistryObject<Item> STEAMED_FISH;
    public static final RegistryObject<Item> SPICY_FISH;
    public static final RegistryObject<Item> BOILED_FISH_WITH_PICKLED_CABBAGE;
    public static final RegistryObject<Item> COKE_CHICKEN_RICE;
    public static final RegistryObject<Item> CURRY_RICE;
    public static final RegistryObject<Item> BOILED_BEEF;
    public static final RegistryObject<Item> PORK_FRIED_PASTA;
    public static final RegistryObject<Item> BEEF_FRIED_PASTA;
    public static final RegistryObject<Item> CHICKEN_FRIED_PASTA;
    public static final RegistryObject<Item> JAPANESE_TOFU_RICE;
    public static final RegistryObject<Item> GOLDEN_GRAPE;
    public static final RegistryObject<Item> COOKED_RICE;
    public static final RegistryObject<Item> CHICKEN_LEG;
    public static final RegistryObject<Item> CHICKEN_WING;
    public static final RegistryObject<Item> POACHED_EGG;
    public static final RegistryObject<Item> PANCAKES;
    public static final RegistryObject<Item> DUMPLING;
    public static final RegistryObject<Item> FRIED_DUMPLING;
    public static final RegistryObject<Item> CHOCOLATE_BAR;
    public static final RegistryObject<Item> TOFU;
    public static final RegistryObject<Item> DEHYDRATED_TOFU;
    public static final RegistryObject<Item> FRIED_POTATO_CHIPS;
    public static final RegistryObject<Item> ZONGZI;
    public static final RegistryObject<Item> TANGYUAN;
    public static final RegistryObject<Item> FRIED_CHICKEN;
    public static final RegistryObject<Item> FRENCH_FRIES;
    public static final RegistryObject<Item> ORLEAN_CHICKEN_WINGS;
    public static final RegistryObject<Item> POPCORN_CHICKEN;
    public static final RegistryObject<Item> ORIGINAL_CHICKEN;
    public static final RegistryObject<Item> DOUGH_TWIST;
    public static final RegistryObject<Item> NIANGAO;
    public static final RegistryObject<Item> CHUNJUAN;
    public static final RegistryObject<Item> FRIED_TOFU;
    public static final RegistryObject<Item> FRIED_NIANGAO;
    public static final RegistryObject<Item> POTATO_CHIPS;
    public static final RegistryObject<Item> FRIED_BREAD;
    public static final RegistryObject<Item> FRIED_CHUNJUAN;
    public static final RegistryObject<Item> FRIED_DOUGH_TWIST;
    public static final RegistryObject<Item> FRIED_CHICKEN_LEG;
    public static final RegistryObject<Item> MOONCAKE;
    public static final RegistryObject<Item> STEAMED_BUNS;
    public static final RegistryObject<Item> SAUERKRAUT_CAKE;
    public static final RegistryObject<Item> YOUTIAO;
    public static final RegistryObject<Item> CHILI_TOFU_STRIP;
    public static final RegistryObject<Item> WALNUT_SHORTBREAD;
    public static final RegistryObject<Item> AICI;
    public static final RegistryObject<Item> CIBA;
    public static final RegistryObject<Item> SAUSAGE;
    public static final RegistryObject<Item> HOT_DOG;
    public static final RegistryObject<Item> BOLONGNA;
    public static final RegistryObject<Item> BACON;
    public static final RegistryObject<Item> FRIED_SAUSAGE;
    public static final RegistryObject<Item> CHEESE;
    public static final RegistryObject<Item> PIZZA;
    public static final RegistryObject<Item> HAMBURGER;
    public static final RegistryObject<Item> SQUID_MEAT;
    public static final RegistryObject<Item> COOKED_SQUID_MEAT;
    public static final RegistryObject<Item> SQUID_SLICE;
    public static final RegistryObject<Item> COOKED_SWEET_POTATO;
    public static final RegistryObject<Item> COOKED_CORN;
    public static final RegistryObject<Item> POPCORN;
    public static final RegistryObject<Item> COOKIE;
    public static final RegistryObject<Item> SMILEY_COOKIE;
    public static final RegistryObject<Item> SOYMILK;
    public static final RegistryObject<Item> HOT_CHOCOLATE;
    public static final RegistryObject<Item> CHOCOLATE_MILK;
    public static final RegistryObject<Item> CARROT_JUICE;
    public static final RegistryObject<Item> APPLE_JUICE;
    public static final RegistryObject<Item> GOLDEN_GRAPE_JUICE;
    public static final RegistryObject<Item> GOLDEN_APPLE_JUICE;
    public static final RegistryObject<Item> SOYBEAN_MILK;
    public static final RegistryObject<Item> COLA;
    public static final RegistryObject<Item> FANTA;
    public static final RegistryObject<Item> SPRITE;
    public static final RegistryObject<Item> MELON_JUICE;
    public static final RegistryObject<Item> TEA;
    public static final RegistryObject<Item> MILK_TEA;
    public static final RegistryObject<Item> COFFEE;
    public static final RegistryObject<Item> SUGAR_WITH_WATER;
    public static final RegistryObject<Item> COCONUT_JUICE_MILK;

    public static final RegistryObject<Item> GOLDEN_APPLE_LIQUEUR;

    public static final RegistryObject<Item> MACHINE_CASING;

    public static Item.Properties foodItem(FoodProperties food) {
        return (new Item.Properties()).food(food);
    }

    public static Item.Properties miscItem() {
        return (new Item.Properties());
    }

    public static RegistryObject<Item> blockItem(RegistryObject<Block> block) {
        return ITEMS.register(block.getId().getPath(), () -> new BlockItem(block.get(), miscItem()));
    }

    static {
        RICE_PORRIDGE = ITEMS.register("rice_porridge", () -> new Item(foodItem(FoodValues.RICE_PORRIDGE)));

        CORN = ITEMS.register("corn", () -> new Item(foodItem(FoodValues.PLANT)));
        CUCUMBER = ITEMS.register("cucumber", () -> new Item(foodItem(FoodValues.PLANT)));
        EGGPLANT = ITEMS.register("eggplant", () -> new Item(foodItem(FoodValues.PLANT)));
        FACING_HEAVEN_PEPPER = ITEMS.register("facing_heaven_pepper", () -> new Item(foodItem(FoodValues.PLANT)));
        GREEN_PEPPER = ITEMS.register("green_pepper", () -> new Item(foodItem(FoodValues.PLANT)));
        PEANUT = ITEMS.register("peanut", () -> new Item(foodItem(FoodValues.PLANT)));
        RICE = ITEMS.register("rice", () -> new Item(foodItem(FoodValues.PLANT)));
        STICKY_RICE = ITEMS.register("sticky_rice", () -> new Item(foodItem(FoodValues.PLANT)));
        SWEET_POTATO = ITEMS.register("sweet_potato", () -> new Item(foodItem(FoodValues.PLANT)));
        TOMATO = ITEMS.register("tomato", () -> new Item(foodItem(FoodValues.PLANT)));
        WHITE_RADISH = ITEMS.register("white_radish", () -> new Item(foodItem(FoodValues.PLANT)));
        CABBAGE = ITEMS.register("cabbage", () -> new Item(foodItem(FoodValues.PLANT)));
        GREEN_ONION = ITEMS.register("green_onion", () -> new Item(foodItem(FoodValues.PLANT)));

        STRAWBERRY = ITEMS.register("strawberry", () -> new Item(foodItem(FoodValues.FRUIT)));
        GRAPEFRUIT = ITEMS.register("grapefruit", () -> new Item(foodItem(FoodValues.FRUIT)));
        CHERRY = ITEMS.register("cherry", () -> new Item(foodItem(FoodValues.FRUIT)));
        COCONUT = ITEMS.register("coconut", () -> new Item(foodItem(FoodValues.FRUIT)));
        BANANA = ITEMS.register("banana", () -> new Item(foodItem(FoodValues.FRUIT)));
        PEACH = ITEMS.register("peach", () -> new Item(foodItem(FoodValues.FRUIT)));
        PERSIMMON = ITEMS.register("persimmon", () -> new Item(foodItem(FoodValues.FRUIT)));
        POMEGRANATE = ITEMS.register("pomegranate", () -> new Item(foodItem(FoodValues.FRUIT)));
        HAWTHORN = ITEMS.register("hawthorn", () -> new Item(foodItem(FoodValues.FRUIT)));
        LOQUAT = ITEMS.register("loquat", () -> new Item(foodItem(FoodValues.FRUIT)));
        LEMON = ITEMS.register("lemon", () -> new Item(foodItem(FoodValues.FRUIT)));
        PAPAYA = ITEMS.register("papaya", () -> new Item(foodItem(FoodValues.FRUIT)));
        LONGAN = ITEMS.register("longan", () -> new Item(foodItem(FoodValues.FRUIT)));
        MANGO = ITEMS.register("mango", () -> new Item(foodItem(FoodValues.FRUIT)));
        LITCHI = ITEMS.register("litchi", () -> new Item(foodItem(FoodValues.FRUIT)));
        PEAR = ITEMS.register("pear", () -> new Item(foodItem(FoodValues.FRUIT)));
        ORANGE = ITEMS.register("orange", () -> new Item(foodItem(FoodValues.FRUIT)));
        DATE = ITEMS.register("date", () -> new Item(foodItem(FoodValues.FRUIT)));

        GRAPEFRUIT_ICE_CREAM = ITEMS.register("grapefruit_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        CHERRY_ICE_CREAM = ITEMS.register("cherry_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        COCONUT_ICE_CREAM = ITEMS.register("coconut_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        BANANA_ICE_CREAM = ITEMS.register("banana_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        PEACH_ICE_CREAM = ITEMS.register("peach_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        PERSIMMON_ICE_CREAM = ITEMS.register("persimmon_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        POMEGRANATE_ICE_CREAM = ITEMS.register("pomegranate_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        HAWTHORN_ICE_CREAM = ITEMS.register("hawthorn_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        LOQUAT_ICE_CREAM = ITEMS.register("loquat_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        LEMON_ICE_CREAM = ITEMS.register("lemon_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        PAPAYA_ICE_CREAM = ITEMS.register("papaya_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        LONGAN_ICE_CREAM = ITEMS.register("longan_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        MANGO_ICE_CREAM = ITEMS.register("mango_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        LITCHI_ICE_CREAM = ITEMS.register("litchi_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        PEAR_ICE_CREAM = ITEMS.register("pear_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        ORANGE_ICE_CREAM = ITEMS.register("orange_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));
        DATE_ICE_CREAM = ITEMS.register("date_ice_cream", () -> new Item(foodItem(FoodValues.FRUIT_ICE_CREAM)));

        GRAPEFRUIT_JAM = ITEMS.register("grapefruit_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        CHERRY_JAM = ITEMS.register("cherry_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        COCONUT_JAM = ITEMS.register("coconut_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        BANANA_JAM = ITEMS.register("banana_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        PEACH_JAM = ITEMS.register("peach_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        PERSIMMON_JAM = ITEMS.register("persimmon_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        POMEGRANATE_JAM = ITEMS.register("pomegranate_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        HAWTHORN_JAM = ITEMS.register("hawthorn_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        LOQUAT_JAM = ITEMS.register("loquat_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        LEMON_JAM = ITEMS.register("lemon_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        PAPAYA_JAM = ITEMS.register("papaya_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        LONGAN_JAM = ITEMS.register("longan_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        MANGO_JAM = ITEMS.register("mango_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        LITCHI_JAM = ITEMS.register("litchi_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        PEAR_JAM = ITEMS.register("pear_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        ORANGE_JAM = ITEMS.register("orange_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));
        DATE_JAM = ITEMS.register("date_jam", () -> new Item(foodItem(FoodValues.FRUIT_JAM)));

        CHOCOLATE_DUST = ITEMS.register("chocolate_dust", () -> new Item(miscItem()));
        IRON_PLATE = ITEMS.register("iron_plate", () -> new Item(miscItem()));
        PURIFIED_WATER = ITEMS.register("purified_water", () -> new Item(miscItem()));
        MILLED_RICE = ITEMS.register("milled_rice", () -> new Item(miscItem()));
        FLOUR = ITEMS.register("flour", () -> new Item(miscItem()));
        PEANUT_OIL = ITEMS.register("peanut_oil", () -> new Item(miscItem()));
        CIRCUIT = ITEMS.register("circuit", () -> new Item(miscItem()));
        DOUGH = ITEMS.register("dough", () -> new Item(miscItem()));
        DUMPLING_MEAT = ITEMS.register("dumpling_meat", () -> new Item(miscItem()));
        SALT = ITEMS.register("salt", () -> new Item(miscItem()));
        SOY_SAUCE = ITEMS.register("soy_sauce", () -> new Item(miscItem()));
        VINEGAR = ITEMS.register("vinegar", () -> new Item(miscItem()));
        POTATO_SLICED = ITEMS.register("potato_sliced", () -> new Item(miscItem()));
        POTATO_SHREDDED = ITEMS.register("potato_shredded", () -> new Item(miscItem()));
        PIXIAN_WATERCRESS = ITEMS.register("pixian_watercress", () -> new Item(miscItem()));
        STARCHES = ITEMS.register("starches", () -> new Item(miscItem()));
        ZONGYE = ITEMS.register("zongye", () -> new Item(miscItem()));
        CURRY = ITEMS.register("curry", () -> new Item(miscItem()));
        STICKY_RICE_FLOUR = ITEMS.register("sticky_rice_flour", () -> new Item(miscItem()));
        STICKY_RICE_DOUGH = ITEMS.register("sticky_rice_dough", () -> new Item(miscItem()));
        PEANUT_TANGYUAN_STUFFING = ITEMS.register("peanut_tangyuan_stuffing", () -> new Item(miscItem()));
        CHICKEN_LARGE = ITEMS.register("chicken_large", () -> new Item(miscItem()));
        CHICKEN_MEDIUM = ITEMS.register("chicken_medium", () -> new Item(miscItem()));
        CHICKEN_SMALL = ITEMS.register("chicken_small", () -> new Item(miscItem()));
        TOFU_SHREDDED = ITEMS.register("tofu_shredded", () -> new Item(miscItem()));
        CARROT_SHREDDED = ITEMS.register("carrot_shredded", () -> new Item(miscItem()));
        DOUGH_SHREDDED = ITEMS.register("dough_shredded", () -> new Item(miscItem()));
        LAWEI_FLAVOR = ITEMS.register("lawei_flavor", () -> new Item(miscItem()));
        WHITE_RADISH_SHREDDED = ITEMS.register("white_radish_shredded", () -> new Item(miscItem()));
        RED_BEAN_PASTE = ITEMS.register("red_bean_paste", () -> new Item(miscItem()));
        JINKELA = ITEMS.register("jinkela", () -> new Item(miscItem()));
        OVERCOOKED_FOOD = ITEMS.register("overcooked_food", () -> new Item(miscItem()));

        EGG_CUSTARD = ITEMS.register("egg_custard", () -> new Item(foodItem(FoodValues.EGG_CUSTARD)));
        MUSHROOM_EGG_SOUP = ITEMS.register("mushroom_egg_soup", () -> new Item(foodItem(FoodValues.MUSHROOM_EGG_SOUP)));
        MUSHROOM_CHICKEN_SOUP = ITEMS.register("mushroom_chicken_soup", () -> new Item(foodItem(FoodValues.MUSHROOM_CHICKEN_SOUP)));
        NOODLES = ITEMS.register("noodles", () -> new Item(foodItem(FoodValues.NOODLES)));
        CROSSING_BRIDGE_NOODLES = ITEMS.register("crossing_bridge_noodles", () -> new Item(foodItem(FoodValues.CROSSING_BRIDGE_NOODLES)));
        PASTA = ITEMS.register("pasta", () -> new Item(foodItem(FoodValues.PASTA)));
        PRESERVED_EGG_PORRIDGE = ITEMS.register("preserved_egg_porridge", () -> new Item(foodItem(FoodValues.PRESERVED_EGG_PORRIDGE)));
        CHANGFEN = ITEMS.register("changfen", () -> new Item(foodItem(FoodValues.CHANGFEN)));
        LABA_PORRIDGE = ITEMS.register("laba_porridge", () -> new Item(foodItem(FoodValues.LABA_PORRIDGE)));
        TOMATO_FRIED_EGG_RICE = ITEMS.register("tomato_fried_egg_rice", () -> new Item(foodItem(FoodValues.TOMATO_FRIED_EGG_RICE)));
        DISANXIAN_RICE = ITEMS.register("disanxian_rice", () -> new Item(foodItem(FoodValues.DISANXIAN_RICE)));
        SHREDDED_PORK_RICE = ITEMS.register("shredded_pork_rice", () -> new Item(foodItem(FoodValues.SHREDDED_PORK_RICE)));
        KUNG_PAO_CHICKEN_RICE = ITEMS.register("kung_pao_chicken_rice", () -> new Item(foodItem(FoodValues.KUNG_PAO_CHICKEN_RICE)));
        FRIED_SHREDDED_POTATO_RICE = ITEMS.register("fried_shredded_potato_rice", () -> new Item(foodItem(FoodValues.FRIED_SHREDDED_POTATO_RICE)));
        FISH_HEAD_RICE = ITEMS.register("fish_head_rice", () -> new Item(foodItem(FoodValues.FISH_HEAD_RICE)));
        MAPO_TOFU_RICE = ITEMS.register("mapo_tofu_rice", () -> new Item(foodItem(FoodValues.MAPO_TOFU_RICE)));
        PORK_BRAISED_IN_BROWN_SAUCE_RICE = ITEMS.register("pork_braised_in_brown_sauce_rice", () -> new Item(foodItem(FoodValues.PORK_BRAISED_IN_BROWN_SAUCE_RICE)));
        TWICE_COOKED_PORK_SLICES_RICE = ITEMS.register("twice_cooked_pork_slices_rice", () -> new Item(foodItem(FoodValues.TWICE_COOKED_PORK_SLICES_RICE)));
        ORLEAN_CHICKEN_WINGS_RICE = ITEMS.register("orlean_chicken_wings_rice", () -> new Item(foodItem(FoodValues.ORLEAN_CHICKEN_WINGS_RICE)));
        SLICED_COLD_CHICKEN = ITEMS.register("sliced_cold_chicken", () -> new Item(foodItem(FoodValues.SLICED_COLD_CHICKEN)));
        SCALLION_CHICKEN = ITEMS.register("scallion_chicken", () -> new Item(foodItem(FoodValues.SCALLION_CHICKEN)));
        CHICKEN_WITH_CHILI_SAUCE = ITEMS.register("chicken_with_chili_sauce", () -> new Item(foodItem(FoodValues.CHICKEN_WITH_CHILI_SAUCE)));
        PEPPERY_CHICKEN = ITEMS.register("peppery_chicken", () -> new Item(foodItem(FoodValues.PEPPERY_CHICKEN)));
        STEAMED_FISH = ITEMS.register("steamed_fish", () -> new Item(foodItem(FoodValues.STEAMED_FISH)));
        SPICY_FISH = ITEMS.register("spicy_fish", () -> new Item(foodItem(FoodValues.SPICY_FISH)));
        BOILED_FISH_WITH_PICKLED_CABBAGE = ITEMS.register("boiled_fish_with_pickled_cabbage", () -> new Item(foodItem(FoodValues.BOILED_FISH_WITH_PICKLED_CABBAGE)));
        COKE_CHICKEN_RICE = ITEMS.register("coke_chicken_rice", () -> new Item(foodItem(FoodValues.COKE_CHICKEN_RICE)));
        CURRY_RICE = ITEMS.register("curry_rice", () -> new Item(foodItem(FoodValues.CURRY_RICE)));
        BOILED_BEEF = ITEMS.register("boiled_beef", () -> new Item(foodItem(FoodValues.BOILED_BEEF)));
        PORK_FRIED_PASTA = ITEMS.register("pork_fried_pasta", () -> new Item(foodItem(FoodValues.PORK_FRIED_PASTA)));
        BEEF_FRIED_PASTA = ITEMS.register("beef_fried_pasta", () -> new Item(foodItem(FoodValues.BEEF_FRIED_PASTA)));
        CHICKEN_FRIED_PASTA = ITEMS.register("chicken_fried_pasta", () -> new Item(foodItem(FoodValues.CHICKEN_FRIED_PASTA)));
        JAPANESE_TOFU_RICE = ITEMS.register("japanese_tofu_rice", () -> new Item(foodItem(FoodValues.JAPANESE_TOFU_RICE)));
        GOLDEN_GRAPE = ITEMS.register("golden_grape", () -> new Item(foodItem(FoodValues.GOLDEN_GRAPE)));
        COOKED_RICE = ITEMS.register("cooked_rice", () -> new Item(foodItem(FoodValues.COOKED_RICE)));
        CHICKEN_LEG = ITEMS.register("chicken_leg", () -> new Item(foodItem(FoodValues.CHICKEN_LEG)));
        CHICKEN_WING = ITEMS.register("chicken_wing", () -> new Item(foodItem(FoodValues.CHICKEN_WING)));
        POACHED_EGG = ITEMS.register("poached_egg", () -> new Item(foodItem(FoodValues.POACHED_EGG)));
        PANCAKES = ITEMS.register("pancakes", () -> new Item(foodItem(FoodValues.PANCAKES)));
        DUMPLING = ITEMS.register("dumpling", () -> new Item(foodItem(FoodValues.DUMPLING)));
        FRIED_DUMPLING = ITEMS.register("fried_dumpling", () -> new Item(foodItem(FoodValues.FRIED_DUMPLING)));
        CHOCOLATE_BAR = ITEMS.register("chocolate_bar", () -> new Item(foodItem(FoodValues.CHOCOLATE_BAR)));
        TOFU = ITEMS.register("tofu", () -> new Item(foodItem(FoodValues.TOFU)));
        DEHYDRATED_TOFU = ITEMS.register("dehydrated_tofu", () -> new Item(foodItem(FoodValues.DEHYDRATED_TOFU)));
        FRIED_POTATO_CHIPS = ITEMS.register("fried_potato_chips", () -> new Item(foodItem(FoodValues.FRIED_POTATO_CHIPS)));
        ZONGZI = ITEMS.register("zongzi", () -> new Item(foodItem(FoodValues.ZONGZI)));
        TANGYUAN = ITEMS.register("tangyuan", () -> new Item(foodItem(FoodValues.TANGYUAN)));
        FRIED_CHICKEN = ITEMS.register("fried_chicken", () -> new Item(foodItem(FoodValues.FRIED_CHICKEN)));
        FRENCH_FRIES = ITEMS.register("french_fries", () -> new Item(foodItem(FoodValues.FRENCH_FRIES)));
        ORLEAN_CHICKEN_WINGS = ITEMS.register("orlean_chicken_wings", () -> new Item(foodItem(FoodValues.ORLEAN_CHICKEN_WINGS)));
        POPCORN_CHICKEN = ITEMS.register("popcorn_chicken", () -> new Item(foodItem(FoodValues.POPCORN_CHICKEN)));
        ORIGINAL_CHICKEN = ITEMS.register("original_chicken", () -> new Item(foodItem(FoodValues.ORIGINAL_CHICKEN)));
        DOUGH_TWIST = ITEMS.register("dough_twist", () -> new Item(foodItem(FoodValues.DOUGH_TWIST)));
        NIANGAO = ITEMS.register("niangao", () -> new Item(foodItem(FoodValues.NIANGAO)));
        CHUNJUAN = ITEMS.register("chunjuan", () -> new Item(foodItem(FoodValues.CHUNJUAN)));
        FRIED_TOFU = ITEMS.register("fried_tofu", () -> new Item(foodItem(FoodValues.FRIED_TOFU)));
        FRIED_NIANGAO = ITEMS.register("fried_niangao", () -> new Item(foodItem(FoodValues.FRIED_NIANGAO)));
        POTATO_CHIPS = ITEMS.register("potato_chips", () -> new Item(foodItem(FoodValues.POTATO_CHIPS)));
        FRIED_BREAD = ITEMS.register("fried_bread", () -> new Item(foodItem(FoodValues.FRIED_BREAD)));
        FRIED_CHUNJUAN = ITEMS.register("fried_chunjuan", () -> new Item(foodItem(FoodValues.FRIED_CHUNJUAN)));
        FRIED_DOUGH_TWIST = ITEMS.register("fried_dough_twist", () -> new Item(foodItem(FoodValues.FRIED_DOUGH_TWIST)));
        FRIED_CHICKEN_LEG = ITEMS.register("fried_chicken_leg", () -> new Item(foodItem(FoodValues.FRIED_CHICKEN_LEG)));
        MOONCAKE = ITEMS.register("mooncake", () -> new Item(foodItem(FoodValues.MOONCAKE)));
        STEAMED_BUNS = ITEMS.register("steamed_buns", () -> new Item(foodItem(FoodValues.STEAMED_BUNS)));
        SAUERKRAUT_CAKE = ITEMS.register("sauerkraut_cake", () -> new Item(foodItem(FoodValues.SAUERKRAUT_CAKE)));
        YOUTIAO = ITEMS.register("youtiao", () -> new Item(foodItem(FoodValues.YOUTIAO)));
        CHILI_TOFU_STRIP = ITEMS.register("chili_tofu_strip", () -> new Item(foodItem(FoodValues.CHILI_TOFU_STRIP)));
        WALNUT_SHORTBREAD = ITEMS.register("walnut_shortbread", () -> new Item(foodItem(FoodValues.WALNUT_SHORTBREAD)));
        AICI = ITEMS.register("aici", () -> new Item(foodItem(FoodValues.AICI)));
        CIBA = ITEMS.register("ciba", () -> new Item(foodItem(FoodValues.CIBA)));
        SAUSAGE = ITEMS.register("sausage", () -> new Item(foodItem(FoodValues.SAUSAGE)));
        HOT_DOG = ITEMS.register("hot_dog", () -> new Item(foodItem(FoodValues.HOT_DOG)));
        BOLONGNA = ITEMS.register("bolongna", () -> new Item(foodItem(FoodValues.BOLONGNA)));
        BACON = ITEMS.register("bacon", () -> new Item(foodItem(FoodValues.BACON)));
        FRIED_SAUSAGE = ITEMS.register("fried_sausage", () -> new Item(foodItem(FoodValues.FRIED_SAUSAGE)));
        CHEESE = ITEMS.register("cheese", () -> new Item(foodItem(FoodValues.CHEESE)));
        PIZZA = ITEMS.register("pizza", () -> new Item(foodItem(FoodValues.PIZZA)));
        HAMBURGER = ITEMS.register("hamburger", () -> new Item(foodItem(FoodValues.HAMBURGER)));
        SQUID_MEAT = ITEMS.register("squid_meat", () -> new Item(foodItem(FoodValues.SQUID_MEAT)));
        COOKED_SQUID_MEAT = ITEMS.register("cooked_squid_meat", () -> new Item(foodItem(FoodValues.COOKED_SQUID_MEAT)));
        SQUID_SLICE = ITEMS.register("squid_slice", () -> new Item(foodItem(FoodValues.SQUID_SLICE)));
        COOKED_SWEET_POTATO = ITEMS.register("cooked_sweet_potato", () -> new Item(foodItem(FoodValues.COOKED_SWEET_POTATO)));
        COOKED_CORN = ITEMS.register("cooked_corn", () -> new Item(foodItem(FoodValues.COOKED_CORN)));
        POPCORN = ITEMS.register("popcorn", () -> new Item(foodItem(FoodValues.POPCORN)));
        COOKIE = ITEMS.register("cookie", () -> new Item(foodItem(FoodValues.COOKIE)));
        SMILEY_COOKIE = ITEMS.register("smiley_cookie", () -> new Item(foodItem(FoodValues.SMILEY_COOKIE)));
        SOYMILK = ITEMS.register("soymilk", () -> new Item(foodItem(FoodValues.SOYMILK)));
        HOT_CHOCOLATE = ITEMS.register("hot_chocolate", () -> new Item(foodItem(FoodValues.HOT_CHOCOLATE)));
        CHOCOLATE_MILK = ITEMS.register("chocolate_milk", () -> new Item(foodItem(FoodValues.CHOCOLATE_MILK)));
        CARROT_JUICE = ITEMS.register("carrot_juice", () -> new Item(foodItem(FoodValues.CARROT_JUICE)));
        APPLE_JUICE = ITEMS.register("apple_juice", () -> new Item(foodItem(FoodValues.APPLE_JUICE)));
        GOLDEN_GRAPE_JUICE = ITEMS.register("golden_grape_juice", () -> new Item(foodItem(FoodValues.GOLDEN_GRAPE_JUICE)));
        GOLDEN_APPLE_JUICE = ITEMS.register("golden_apple_juice", () -> new Item(foodItem(FoodValues.GOLDEN_APPLE_JUICE)));
        SOYBEAN_MILK = ITEMS.register("soybean_milk", () -> new Item(foodItem(FoodValues.SOYBEAN_MILK)));
        COLA = ITEMS.register("cola", () -> new Item(foodItem(FoodValues.COLA)));
        FANTA = ITEMS.register("fanta", () -> new Item(foodItem(FoodValues.FANTA)));
        SPRITE = ITEMS.register("sprite", () -> new Item(foodItem(FoodValues.SPRITE)));
        MELON_JUICE = ITEMS.register("melon_juice", () -> new Item(foodItem(FoodValues.MELON_JUICE)));
        TEA = ITEMS.register("tea", () -> new Item(foodItem(FoodValues.TEA)));
        MILK_TEA = ITEMS.register("milk_tea", () -> new Item(foodItem(FoodValues.MILK_TEA)));
        COFFEE = ITEMS.register("coffee", () -> new Item(foodItem(FoodValues.COFFEE)));
        SUGAR_WITH_WATER = ITEMS.register("sugar_with_water", () -> new Item(foodItem(FoodValues.SUGAR_WITH_WATER)));
        COCONUT_JUICE_MILK = ITEMS.register("coconut_juice_milk", () -> new Item(foodItem(FoodValues.COCONUT_JUICE_MILK)));

        GOLDEN_APPLE_LIQUEUR = ITEMS.register("golden_apple_liqueur", () -> new Item(foodItem(FoodValues.LIQUEUR)));

        MACHINE_CASING = blockItem(ModBlocks.MACHINE_CASING);
    }
}
